package org.onstage.enums;

public enum NotificationType {
    TEAM_INVITATION_REQUEST,
    TEAM_INVITATION_ACCEPTED,
    TEAM_INVITATION_DECLINED,
    TEAM_MEMBER_REMOVED,
    EVENT_INVITATION_REQUEST,
    EVENT_INVITATION_ACCEPTED,
    EVENT_INVITATION_DECLINED,
    LEAD_VOICE_ASSIGNED,
    EVENT_DELETED,
    REMINDER,
    NEW_REHEARSAL,
    ROLE_CHANGED
}
