package org.onstage.enums;

public enum RevenueCatEventType {
    TEST,
    INITIAL_PURCHASE,
    NON_RENEWING_PURCHASE,
    RENEWAL,
    PRODUCT_CHANGE,
    CANCELLATION,
    UNCANCELLATION,
    BILLING_ISSUE,
    SUBSCRIBER_ALIAS,
    SUBSCRIPTION_PAUSED,
    TRANSFER,
    EXPIRATION

}
